#
# Cookbook:: test
# Recipe:: cleanup
#
# Copyright:: 2018, Ben Hughes <bmhughes@bmhughes.co.uk>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repo_config = '
# This file was generated by Chef
# Do NOT modify this file by hand.

[syslog-ng312]
name=Copr repo for syslog-ng320 owned by czanik
baseurl=https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng312/fedora-$releasever-$basearch/
enabled=1
fastestmirror_enabled=0
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng312/pubkey.gpg
skip_if_unavailable=1
enabled_metadata=1
type=rpm-md
'

file '/etc/yum.repos.d/syslog-ng312.repo' do
  content repo_config
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end
